#!/usr/bin/env python3
"""Generate CaseDambreakVal2D_Def.xml: 2D dam-break validation case.

Reproduces, as a programmatically generated MIT-licensed file, the geometry
and numerical setup of the official DualSPHysics validation case
``examples/main/01_DamBreak/CaseDambreakVal2D_Def.xml`` (DualSPHysics is
LGPL-2.1+; only the numerical parameters are reused, no file is copied):

- dp = 0.01 m, 2D (the y extent of the geometry is clamped to the y=0 plane
  because the domain definition has y_min == y_max)
- water column: 1 m long x 2 m high at the origin
- tank: 4 m long x 3 m high, closed bottom/left/right, open top
- TimeMax = 2 s, TimeOut = 0.01 s (201 part files)
- two SWL gauges (free-surface probes at x=0.2 and along z=0.03)
- Verlet time stepping, Wendland kernel, artificial viscosity 0.02,
  Fourtakas density diffusion 0.1, CFL 0.2

Validation target: dam-tip (surge front) position vs Koshizuka & Oka (1996);
the digitised series ships next to this script as
experimental_damtip_koshizuka_oka_1996.csv.

Usage:
    python gen_dambreak_val2d.py [--output CaseDambreakVal2D_Def.xml]
"""

from __future__ import annotations

import argparse
from pathlib import Path

DEFAULT_OUTPUT = Path(__file__).resolve().parent / "CaseDambreakVal2D_Def.xml"

CASE_TEMPLATE = """<?xml version="1.0" encoding="UTF-8" ?>
<!-- 2D dam-break validation case (Koshizuka & Oka 1996 layout).
     Generated by gen_dambreak_val2d.py -- dualsphysics-mcp examples. -->
<case>
    <casedef>
        <constantsdef>
            <gravity x="0" y="0" z="-{gravity:g}" comment="Gravitational acceleration" units_comment="m/s^2" />
            <rhop0 value="{rhop0}" comment="Reference density of the fluid" units_comment="kg/m^3" />
            <rhopgradient value="2" comment="Initial density gradient 1:Rhop0, 2:Water column, 3:Max. water height (default=2)" />
            <hswl value="0" auto="true" comment="Maximum still water level to calculate speedofsound using coefsound" units_comment="metres (m)" />
            <gamma value="7" comment="Polytropic constant for water used in the state equation" />
            <speedsystem value="0" auto="true" comment="Maximum system speed (by default the dam-break propagation is used)" />
            <coefsound value="20" comment="Coefficient to multiply speedsystem" />
            <speedsound value="0" auto="true" comment="Speed of sound (by default speedofsound=coefsound*speedsystem)" />
            <coefh value="1.0" comment="Coefficient to calculate the smoothing length (h=coefh*sqrt(3*dp^2) in 3D)" />
            <cflnumber value="{cfl}" comment="Coefficient to multiply dt" />
        </constantsdef>
        <mkconfig boundcount="240" fluidcount="9" />
        <geometry>
            <definition dp="{dp}" units_comment="metres (m)">
                <pointref x="0" y="0" z="0" />
                <pointmin x="{domain_margin}" y="0" z="{domain_margin}" />
                <pointmax x="{domain_x_max_margin}" y="0" z="{domain_z_max_margin}" />
            </definition>
            <commands>
                <mainlist>
                    <setdrawmode mode="full" />
                    <setmkfluid mk="0" />
                    <drawbox>
                        <boxfill>solid</boxfill>
                        <point x="0" y="-1" z="0" />
                        <size x="{column_length}" y="2" z="{column_height}" />
                    </drawbox>
                    <setmkbound mk="0" />
                    <drawbox>
                        <boxfill>bottom | left | right | front | back</boxfill>
                        <point x="0" y="-1" z="0" />
                        <size x="{domain_x}" y="2" z="{domain_z}" />
                    </drawbox>
                </mainlist>
            </commands>
        </geometry>
    </casedef>
    <execution>
        <special>
            <gauges>
                <default>
                    <savevtkpart value="true" comment="Creates VTK files for each PART (default=false)" />
                    <output value="true" comment="Creates CSV files of measurements (default=false)" />
                </default>
                <swl name="Swl_x02">
                    <pointdp coefdp="0.5" comment="Distance between check points (value=coefdp*Dp)" />
                    <point0 x="{gauge_x}" y="0" z="-0.05" comment="Initial point" units_comment="m" />
                    <point2 x="{gauge_x}" y="0" z="{gauge_z_top}" comment="Final point" units_comment="m" />
                </swl>
                <swl name="Swl_z003">
                    <computedt value="0.005" comment="Time between measurements (default=default.computedt)" units_comment="s" />
                    <outputdt value="0.005" comment="Time between output measurements (default=default.outputdt)" units_comment="s" />
                    <pointdp coefdp="0.5" comment="Distance between check points (value=coefdp*Dp)" />
                    <point0 x="-0.05" y="0" z="{gauge_z}" comment="Initial point" units_comment="m" />
                    <point2 x="{gauge_x_end}" y="0" z="{gauge_z}" comment="Final point" units_comment="m" />
                </swl>
            </gauges>
        </special>
        <parameters>
            <parameter key="SavePosDouble" value="0" comment="Saves particle position using double precision (default=0)" />
            <parameter key="StepAlgorithm" value="1" comment="Step Algorithm 1:Verlet, 2:Symplectic (default=1)" />
            <parameter key="VerletSteps" value="40" comment="Verlet only: Number of steps to apply Euler timestepping (default=40)" />
            <parameter key="Kernel" value="2" comment="Interaction Kernel 1:Cubic Spline, 2:Wendland (default=2)" />
            <parameter key="ViscoTreatment" value="1" comment="Viscosity formulation 1:Artificial, 2:Laminar+SPS, 3:Laminar (default=1)" />
            <parameter key="Visco" value="{visco}" comment="Viscosity value (artificial alpha)" />
            <parameter key="ViscoBoundFactor" value="1" comment="Multiply viscosity value with boundary (default=1)" />
            <parameter key="DensityDT" value="2" comment="Density Diffusion Term 0:None, 1:Molteni, 2:Fourtakas, 3:Fourtakas(full) (default=0)" />
            <parameter key="DensityDTvalue" value="0.1" comment="DDT value (default=0.1)" />
            <parameter key="Shifting" value="0" comment="Shifting mode 0:None, 1:Ignore bound, 2:Ignore fixed, 3:Full (default=0)" />
            <parameter key="ShiftCoef" value="-2" comment="Coefficient for shifting computation (default=-2)" />
            <parameter key="ShiftTFS" value="0" comment="Threshold to detect free surface (default=0)" />
            <parameter key="RigidAlgorithm" value="1" comment="Rigid Algorithm 0:collision-free, 1:SPH, 2:DEM, 3:Chrono (default=1)" />
            <parameter key="FtPause" value="0.0" comment="Time to freeze the floatings at simulation start (default=0)" units_comment="seconds" />
            <parameter key="CoefDtMin" value="0.05" comment="Coefficient to calculate minimum time step dtmin=coefdtmin*h/speedsound (default=0.05)" />
            <parameter key="DtIni" value="0" comment="Initial time step (default=h/speedsound)" units_comment="seconds" />
            <parameter key="DtMin" value="0" comment="Minimum time step (default=coefdtmin*h/speedsound)" units_comment="seconds" />
            <parameter key="DtFixed" value="0" comment="Fixed Dt value (0=disabled)" units_comment="seconds" />
            <parameter key="DtAllParticles" value="0" comment="Velocity of particles used to calculate DT. 1:All, 0:Only fluid/floating (default=0)" />
            <parameter key="TimeMax" value="{tmax}" comment="Time of simulation" units_comment="seconds" />
            <parameter key="TimeOut" value="{tout}" comment="Time out data" units_comment="seconds" />
            <parameter key="PartsOutMax" value="1" comment="%/100 of fluid particles allowed to be excluded from domain (default=1)" units_comment="decimal" />
            <parameter key="RhopOutMin" value="700" comment="Minimum rhop valid (default=700)" units_comment="kg/m^3" />
            <parameter key="RhopOutMax" value="1300" comment="Maximum rhop valid (default=1300)" units_comment="kg/m^3" />
            <simulationdomain comment="Domain of simulation (default=uses min/max position of generated particles)">
                <posmin x="default" y="default" z="default" />
                <posmax x="default" y="default" z="default" />
            </simulationdomain>
        </parameters>
    </execution>
</case>
"""


def build_case_xml(
    dp: float = 0.01,
    column_length: float = 1.0,
    column_height: float = 2.0,
    domain_x: float = 4.0,
    domain_z: float = 3.0,
    tmax: float = 2.0,
    tout: float = 0.01,
    gravity: float = 9.81,
    rhop0: int = 1000,
    cfl: float = 0.2,
    visco: float = 0.02,
    gauge_x: float = 0.2,
    gauge_z: float = 0.03,
) -> str:
    """Render the case XML from the validation parameters."""
    return CASE_TEMPLATE.format(
        dp=dp,
        column_length=column_length,
        column_height=column_height,
        domain_x=domain_x,
        domain_z=domain_z,
        domain_margin=-1,
        domain_x_max_margin=domain_x + 0.5,
        domain_z_max_margin=domain_z + 0.5,
        tmax=tmax,
        tout=tout,
        gravity=gravity,
        rhop0=rhop0,
        cfl=cfl,
        visco=visco,
        gauge_x=gauge_x,
        gauge_z=gauge_z,
        gauge_z_top=column_height + 0.1,
        gauge_x_end=domain_x + 0.05,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output XML path")
    parser.add_argument("--dp", type=float, default=0.01, help="Initial inter-particle spacing (m)")
    parser.add_argument("--tmax", type=float, default=2.0, help="Simulated time (s)")
    parser.add_argument("--tout", type=float, default=0.01, help="Time between part files (s)")
    args = parser.parse_args()

    xml = build_case_xml(dp=args.dp, tmax=args.tmax, tout=args.tout)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(xml, encoding="utf-8")
    print(f"wrote {args.output}")
    print(
        "next: gencase(xml_path=...) -> run_case -> job_status -> partvtk / "
        "measure_tool(points_file='points_damtip.txt') -> validate_dambreak"
    )


if __name__ == "__main__":
    main()
